# Generated by Django 4.2.11 on 2024-10-18 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Назва відділення')),
            ],
            options={
                'verbose_name': 'Відділення спортзалу',
                'verbose_name_plural': 'Відділення спортзалу',
                'db_table': 'departament',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Від')),
                ('end_date', models.DateTimeField(verbose_name='До')),
                ('active', models.BooleanField(default=True, verbose_name='Чи активна')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Дата створення')),
            ],
            options={
                'verbose_name': 'Резервація часу',
                'verbose_name_plural': 'Резервації часу',
                'db_table': 'reservations',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Понеділок'), (1, 'Вівторок'), (2, 'Середа'), (3, 'Четвер'), (4, "П'ятниця"), (5, 'Субота'), (6, 'Неділя')], default=0, verbose_name='День неділі')),
                ('start_time', models.TimeField(default=datetime.time(9, 0), verbose_name='Час початку роботи')),
                ('end_time', models.TimeField(default=datetime.time(17, 0), verbose_name='Час завершення роботи')),
            ],
            options={
                'verbose_name': 'Розклад роботи тренера',
                'verbose_name_plural': 'Розклад роботи тренерів',
                'db_table': 'work_schedules',
                'ordering': ['trainer', 'day_of_week'],
            },
        ),
    ]
