# Generated by Django 4.2.11 on 2024-11-17 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_workschedule_trainer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workschedule',
            options={'ordering': ['trainer', 'start_time'], 'verbose_name': 'Розклад роботи тренера', 'verbose_name_plural': 'Розклад роботи тренерів'},
        ),
        migrations.RemoveConstraint(
            model_name='workschedule',
            name='unique_trainer_day',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='active',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='day_of_week',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_date',
            field=models.DateTimeField(verbose_name='Кінець резервації'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_date',
            field=models.DateTimeField(verbose_name='Початок резервації'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='end_time',
            field=models.DateTimeField(verbose_name='Час завершення роботи'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='start_time',
            field=models.DateTimeField(verbose_name='Час початку роботи'),
        ),
    ]
