# Generated by Django 4.2.11 on 2024-11-17 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_workschedule_options_and_more'),
        ('users', '0004_trainerprofile_departaments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerprofile',
            name='departaments',
            field=models.ManyToManyField(blank=True, related_name='trainers', to='booking.departament', verbose_name='Відділення у яких працює тренер'),
        ),
    ]
